# Generated by Django 5.2.3 on 2025-06-13 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('temperature', models.FloatField()),
                ('threshold', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                (
                    'location',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alerts',
                        to='location.location',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('temperature_threshold', models.FloatField()),
                ('check_interval_minutes', models.IntegerField(default=30)),
                (
                    'location',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alert_config',
                        to='location.location',
                    ),
                ),
            ],
        ),
    ]
