# Generated by Django 5.2.3 on 2025-06-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                (
                    'location',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='temperature_logs',
                        to='location.location',
                    ),
                ),
            ],
        ),
    ]
