# Generated by Django 5.2.3 on 2025-06-13 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfig',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='alert_config',
                to='location.location',
            ),
        ),
    ]
